import './globals.css'
import Nav from '../components/header/nav'
import styles from './main.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Nav />
      <body>{children}</body>
    </html>
  )
}
